--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.470.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 09-02-2021 17:05:53
-- Server version: 8.0.21
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set default database
--
USE online_banking_transaction_system;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `account`
--
DROP TABLE IF EXISTS account;

--
-- Drop table `fd`
--
DROP TABLE IF EXISTS fd;

--
-- Drop table `customer`
--
DROP TABLE IF EXISTS customer;

--
-- Set default database
--
USE online_banking_transaction_system;

--
-- Create table `customer`
--
CREATE TABLE customer (
  CUST_ID INT NOT NULL AUTO_INCREMENT,
  First_Name VARCHAR(50) NOT NULL,
  Middle_Name VARCHAR(50) DEFAULT ' ',
  Last_Name VARCHAR(50) NOT NULL,
  DOB DATE DEFAULT NULL,
  Gender VARCHAR(10) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Contact VARCHAR(50) NOT NULL,
  PAN VARCHAR(20) NOT NULL,
  Nationality VARCHAR(10) NOT NULL,
  Salary DECIMAL(18, 2) DEFAULT 0.00,
  Street VARCHAR(50) NOT NULL,
  City VARCHAR(50) NOT NULL,
  State VARCHAR(50) NOT NULL,
  Pin VARCHAR(50) NOT NULL,
  PRIMARY KEY (CUST_ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 23,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `fd`
--
CREATE TABLE fd (
  FD_ID INT NOT NULL AUTO_INCREMENT,
  CUST_ID INT NOT NULL,
  Balance DECIMAL(18, 2) NOT NULL,
  PRIMARY KEY (FD_ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE fd 
  ADD CONSTRAINT fd_ibfk_1 FOREIGN KEY (CUST_ID)
    REFERENCES customer(CUST_ID);

--
-- Create table `account`
--
CREATE TABLE account (
  Acc_ID INT NOT NULL AUTO_INCREMENT,
  Acc_No VARCHAR(20) NOT NULL,
  Cust_ID INT NOT NULL,
  Balance DECIMAL(18, 2) NOT NULL,
  PRIMARY KEY (Acc_No),
  UNIQUE INDEX Acc_ID(Acc_ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create foreign key
--
ALTER TABLE account 
  ADD CONSTRAINT account_ibfk_1 FOREIGN KEY (Cust_ID)
    REFERENCES customer(CUST_ID);

--
-- Create foreign key
--
ALTER TABLE account 
  ADD CONSTRAINT FK9y85nxkfpucu706yjrnxu7u7j FOREIGN KEY (Cust_ID)
    REFERENCES customer(CUST_ID);

--
-- Create table `employee`
--
CREATE TABLE employee (
  Emp_ID INT NOT NULL AUTO_INCREMENT,
  First_Name VARCHAR(50) NOT NULL,
  Middle_Name VARCHAR(50) DEFAULT ' ',
  Last_Name VARCHAR(50) NOT NULL,
  DOB DATE NOT NULL,
  Gender VARCHAR(10) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Contact VARCHAR(50) NOT NULL,
  PAN VARCHAR(20) NOT NULL,
  Nationality VARCHAR(10) NOT NULL,
  Salary DECIMAL(18, 2) NOT NULL,
  Street VARCHAR(50) NOT NULL,
  City VARCHAR(50) NOT NULL,
  State VARCHAR(50) NOT NULL,
  Pin VARCHAR(50) NOT NULL,
  PRIMARY KEY (Emp_ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table customer
--
INSERT INTO customer VALUES
(17, 'VAIBHAV', '', 'GANGWAR', '1996-07-30', 'Male', 'vaibhavgangwar96@gmail.com', '12345', '9457085634', 'BIDPG1388R', 'Indian', 80000.00, 'Ghitorni Lake Road', 'New Delhi', 'Delhi', '110030'),
(18, 'Rahul', '', 'Patel', '1996-03-15', 'Male', 'rahulpatel@gmail.com', '12345', '1234567890', 'BIDPG13990', 'Indian', 80000.00, 'Surya Enclave Pilibhit Bypass Road ', 'Bareilly', 'Uttar Pradesh', '243006'),
(19, 'Rahul', '', 'Kulhade', '1996-03-13', 'Male', 'rahulkulhade@gmail.com', '12345', '7096538273', 'BIGVM1388R', 'Indian', 70000.00, 'chandni chowk,old delhi', 'delhi', 'delhi', '110001'),
(20, 'Ajay', 'Kumar', 'Gangwar', '2021-03-03', 'Male', 'ajayapril1991@gmail.com', '12345', '7042502002', 'BIDPG1388R', 'Indian', 0.00, 'GCM SAVITRI APARTMENT', 'New Delhi South West', 'Delhi', '110030'),
(22, 'AJAY', '', 'GANGWAR', '1991-06-30', 'MALE', 'AJAYGANGWAR96@GMAIL.COM', '123QWERT', '0000000000', 'ARQPH1415H', 'INDIAN', 0.00, 'GHITORNI LAKE ROAD', 'DELHI', 'DELHI', '110030');

-- 
-- Dumping data for table fd
--
INSERT INTO fd VALUES
(4, 17, 0.00),
(5, 18, 1000.00),
(6, 19, 2500.00),
(7, 20, 3400.00);

-- 
-- Dumping data for table employee
--
INSERT INTO employee VALUES
(4, 'Admin', '', '123', '1991-06-30', 'MALE', 'admin@gmail.com', '12345', '7042502002', 'ARQPH1415H', 'Indian', 0.00, 'Ghitorni Lake Road', 'Ghitorni', 'Delhi', '110030');

-- 
-- Dumping data for table account
--
INSERT INTO account VALUES
(9, 'RVR0000000000', 22, 160000.00),
(6, 'RVR1234567890', 18, 160241.00),
(8, 'RVR7042502002', 20, 166059.00),
(7, 'RVR7096538273', 19, 160000.00),
(5, 'RVR9457085634', 17, 153700.00);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;